<link href="css/bootstrap.min.css" rel="stylesheet">
<link href="css/bootstrap-theme.min.css" rel="stylesheet">
<link href="css/jquery.smartmenus.bootstrap.css" rel="stylesheet">
<link href="css/jquery-ui.css" rel="stylesheet">
<link href="css/jquery-ui.custom.css" rel="stylesheet">
<link href="css/font-awesome.min.css" rel="stylesheet">
<link href="css/lightslider.css" rel="stylesheet">
<link href="css/style.css?v3.1" rel="stylesheet">
<link href="css/media.css?v3.1" rel="stylesheet">
<link href="css/fonts.css" rel="stylesheet">
